### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by EMolinos** [lagadic/vrep_ros_bridge#32]
Hello:

I'm trying to install the vrep_ros_bridge package without success. I'm working under Ubuntu 12.04 and ROS Hydro distribution.

I followed the installation tutorials, but when i execute catkin_make in my workspace this error appears:

Building CXX object vrep_ros_bridge-indigo-devel/vrep_ros_plugin/src/CMakeFiles/v_repExtRosBridge.dir/v_repExtRosBridge.cpp.o
[ 37%] Building CXX object vrep_ros_bridge-indigo-devel/vrep_ros_plugin/src/CMakeFiles/v_repExtRosBridge.dir/GenericObjectContainer.cpp.o
/opt/ros/hydro/include/pluginlib/class_loader_imp.h: In member function ‘std::string pluginlib::ClassLoader<T>::extractPackageNameFromPackageXML(const string&)’:
/opt/ros/hydro/include/pluginlib/class_loader_imp.h:210:41: error: no matching function for call to ‘TiXmlDocument::LoadFile(const string&)’
/opt/ros/hydro/include/pluginlib/class_loader_imp.h: In member function ‘void pluginlib::ClassLoader<T>::processSingleXMLPluginFile(const string&, std::map<std::basic_string<char>, pluginlib::ClassDesc>&)’:
/opt/ros/hydro/include/pluginlib/class_loader_imp.h:545:31: error: no matching function for call to ‘TiXmlDocument::LoadFile(const string&)’
/opt/ros/hydro/include/pluginlib/class_loader_imp.h:552:17: error: ‘class TiXmlElement’ has no member named ‘ValueStr’
/opt/ros/hydro/include/pluginlib/class_loader_imp.h:553:17: error: ‘class TiXmlElement’ has no member named ‘ValueStr’
/opt/ros/hydro/include/pluginlib/class_loader_imp.h:560:17: error: ‘class TiXmlElement’ has no member named ‘ValueStr’
/opt/ros/hydro/include/pluginlib/class_loader_imp.h: In member function ‘std::string pluginlib::ClassLoader<T>::extractPackageNameFromPackageXML(const string&)’:
/opt/ros/hydro/include/pluginlib/class_loader_imp.h:210:41: error: no matching function for call to ‘TiXmlDocument::LoadFile(const string&)’
/opt/ros/hydro/include/pluginlib/class_loader_imp.h: In member function ‘void pluginlib::ClassLoader<T>::processSingleXMLPluginFile(const string&, std::map<std::basic_string<char>, pluginlib::ClassDesc>&)’:
/opt/ros/hydro/include/pluginlib/class_loader_imp.h:545:31: error: no matching function for call to ‘TiXmlDocument::LoadFile(const string&)’
/opt/ros/hydro/include/pluginlib/class_loader_imp.h:552:17: error: ‘class TiXmlElement’ has no member named ‘ValueStr’
/opt/ros/hydro/include/pluginlib/class_loader_imp.h:553:17: error: ‘class TiXmlElement’ has no member named ‘ValueStr’
/opt/ros/hydro/include/pluginlib/class_loader_imp.h:560:17: error: ‘class TiXmlElement’ has no member named ‘ValueStr’

Any idea about this problem? My ROS Hydro packages are updated to last version. Thank you in advance!

**Comment by EMolinos** [comment]
I am able to solve the installation problem. It is not a problem with VREP_ROS_BRIDGE, is a problem with pluginlib libraries.

Modifying /opr/ros/hydro/include/pluginlib/class_loader.h, including "#define  TIXML_USE_STL" just before #include "tinyxml.h" solves the problem.

**Comment by fabrizioschiano** [comment]
Thanks for posting the solution of your problem. 

Fabrizio.
