### ISSUE TITLE
telekyb_msgs not existing in Indigo/14.04?

### ISSUE THREAD

**Issue by peci1** [lagadic/vrep_ros_bridge#35]
I can't find anything on Indigo that would satisfy the `telekyb_msgs` dependency from quadrotor_TK_handler. Should you add this message package to the repo?

Especially:

    rosdep resolve telekyb_msgs
    ERROR: no rosdep rule for 'telekyb_msgs'

**Comment by ricsp** [comment]
Hi,
I guess you have already found a solution. Anyway, telekyb_msgs is part of [Telekyb] (http://wiki.ros.org/telekyb) a ros-based middleware for quadrotor control. I doubt that you need it. If not just put a file named CATKIN_IGNORE in the quadrotor_tk_handler plugin folder and the rest should compile smoothly.
Cheers.
Riccardo
