### ISSUE TITLE
When v-rep initiates

### ISSUE THREAD

**Issue by auroraqian** [lagadic/vrep_ros_bridge#36]
So I installed the plugin following the instructions, but when I initiate vrep, it shows
Simulator launched.
Plugin 'Dynamics': loading...
Plugin 'Dynamics': load succeeded.
Plugin 'BubbleRob': loading...
Plugin 'BubbleRob': load succeeded.
Plugin 'Collada': loading...
Plugin 'Collada': load succeeded.
Plugin 'K3': loading...
Plugin 'K3': load succeeded.
Plugin 'LuaRemoteApiClient': loading...
Plugin 'LuaRemoteApiClient': load succeeded.
Plugin 'Mtb': loading...
Plugin 'Mtb': load succeeded.
Plugin 'OpenMesh': loading...
Plugin 'OpenMesh': load succeeded.
Plugin 'RRS1': loading...
Plugin 'RRS1': load succeeded.
Plugin 'ReflexxesTypeIV': loading...
Plugin 'ReflexxesTypeIV': load succeeded.
Plugin 'RemoteApi': loading...
Starting a remote API server on port 19997
Plugin 'RemoteApi': load succeeded.
Plugin 'Ros': loading...
Plugin 'Ros': load succeeded.
Plugin 'RosBridge': loading...
[rospack] Warning: no such package vrep_ros_plugin
-------------------------------------------------------------------
Available ObjectHandlers: 
Plugin 'RosBridge': load succeeded.
Plugin 'SimpleFilter': loading...
Plugin 'SimpleFilter': load succeeded.
Plugin 'Urdf': loading...
Plugin 'Urdf': load succeeded.
Plugin 'Vision': loading...
Plugin 'Vision': load succeeded.
Using the internal 'MeshCalc' functionality.
Using the 'Dynamics' plugin.
Using the internal 'PathPlanning' functionality.

**Comment by jokla** [comment]
Maybe the link is not set correctly (It should point the real library libv_repExtRosBridge.so placed in your devel/lib folder of ROS).

Can you go via terminal in the V-REP folder  and execute:

ll libv_repExtRosBridge.so

you should see something like:

libv_repExtRosBridge.so -> /home/catkin_ws/devel/lib/libv_repExtRosBridge.so*

If not, you have to create again the link using the instruction:

ln -s /YOUR_CATKIN_WS_PATH/devel/lib/libv_repExtRosBridge.so

Let me know,

Giovanni

**Comment by auroraqian** [comment]
I typed in ll libv_repExtRosBridge.so, and I saw  libv_repExtRosBridge.so -> /home/catkin_ws/devel/lib/libv_repExtRosBridge.so*. But when I run vrep the same error is still there. Could you think of something else that might cause this error? Thanks!

**Comment by auroraqian** [comment]
I manage to solve this problem by source devel/setup.bash. Thanks a lot!~

**Comment by jokla** [comment]
Very good, I will add it to the guide to avoid this problem.

Thank you for the feedback
