### ISSUE TITLE
Can't load examples

### ISSUE THREAD

**Issue by auroraqian** [lagadic/vrep_ros_bridge#37]
Every time I open  Pioneer_p3dx example, v_rep will shut down and on the terminal it shows
Instantiating new ManipulatorHandler for Pioneer_p3dx.
QMetaType::registerType: Binary compatibility break -- Size mismatch for type 'QPaintBufferCacheEntry' [1024]. Previously registered size 16, now registering size 0.
Aborted (core dumped)

**Comment by jokla** [comment]
Hi,
which version of Vrep and Ubuntu are you using?

**Comment by auroraqian** [comment]
I am using 14.04 and yes the same problem even exists with Test.ttt.
But I just reinstall everything, including vrep_ros_bridge and demo_pioneer on another Ubuntu 14.04 and it works, so now I am not sure if it is just because something weird happened to that specific computer.

**Comment by fabrizioschiano** [comment]
Let us know if you experience again this problem.

Fabrizio
