### ISSUE TITLE
Compat with V-REP 3.1 or higher

### ISSUE THREAD

**Issue by fspindle** [lagadic/vrep_ros_bridge#38]
I just installed V-REP 3.2.1 and have the following warning that appears in a window when I try to test the plugin with vrep_ros_bridge/SceneVrep/Test.ttt

Compatibility issue with MAIN SCRIPT
Since V-REP 3.1.3, the functions simHandleChildScript and simHandleSensingChildScripts
were replaced with simHandleChildScripts (i.e. with an additional 's'), which
operates slightly differently. In addition to this, a new function was introduced that
handles threaded child scripts: simLaunchThreadedChildScripts. For that reason, V-REP
has automatically adjusted the customized main script. Make sure that everything
still works as expected.

Since simHandleChildScript and simHandleSensingChildScripts are not used in vrep_ros_bridge it sounds to me that this message could be ignored. 

Can you confirm ?

**Comment by jokla** [comment]
Yes you can ignore that. It is about the [main script](http://www.coppeliarobotics.com/helpFiles/en/mainScript.htm) in LUA (You can find there the function simHandleChildScripts). In the new version they changed it.

Giovanni
