### ISSUE TITLE
Help..  Packages "vrep_ros_bridge" not found in the workspace

### ISSUE THREAD

**Issue by johnjavz** [lagadic/vrep_ros_bridge#43]
Hi Giovanni and Ricardo,

I have tried to set the vrep_ros_bridge, with the corresponding indications. Or it does not compile the ibv_repExtRosBridge.so file. I need help. The error is Packages "vrep_ros_bridge" not found in the workspace. I use ubuntu 14.04 and  ROS Indigo.

Att,

John J.

----------------------------------------------------------------------------------------------------------------------------------------
john@john-Vostro-1400:~/catkin_ws$ catkin_make
Base path: /home/john/catkin_ws
Source space: /home/john/catkin_ws/src
Build space: /home/john/catkin_ws/build
Devel space: /home/john/catkin_ws/devel
Install space: /home/john/catkin_ws/install
####
####
####
####
john@john-Vostro-1400:~/catkin_ws$ catkin_make --pkg vrep_ros_bridge --cmake-args -DCMAKE_BUILD_TYPE=RelWithDebInfo
Base path: /home/john/catkin_ws
Source space: /home/john/catkin_ws/src
Build space: /home/john/catkin_ws/build
Devel space: /home/john/catkin_ws/devel
Install space: /home/john/catkin_ws/install
Packages "vrep_ros_bridge" not found in the workspace

**Comment by fabrizioschiano** [comment]
Hi, 

It looks like ROS is not aware that there is a vrep_ros_bridge package. 

I would try to :
`source  /path/to/your/catkin_ws/devel/setup.bash`

Let us know what happens and if you solve your problem.

Fabrizio.

**Comment by jokla** [comment]
Hi, 

Fabrizio is right, if you want you can add all the commands in the ~/.bashrc:

Run in the terminal:
`gedit ~/.bashrc`

and add at the end of the file the following lines (probably you already did it if you have followed the tutorial). Substitute jokla with your user name and the path with the right one:
____________________________________________
# ROS
export ROS_PACKAGE_PATH=${ROS_PACKAGE_PATH}:/home/jokla/catkin_ws/src
source /opt/ros/indigo/setup.bash
source /home/jokla/catkin_ws/devel/setup.bash

#V-REP
export VREP_ROOT_DIR=/home/jokla/Romeo/SOFT/3rd_PARTY/V-REP
________________________________________________

Save the file, open a new terminal and try... 

Let us know if this solve the problem please,

Giovanni

**Comment by johnjavz** [comment]
Hi, 

perform the procedure that I indicated. It does not work. attached images of the procedure.

Thanks for the support.

![uno](https://cloud.githubusercontent.com/assets/14174212/9747078/65570b48-5630-11e5-8d0f-e86e5437986b.png)

This error:          git checkout indigo-devel

![tres](https://cloud.githubusercontent.com/assets/14174212/9747123/c03d07ba-5630-11e5-9a47-6cf4ccaceb7f.png)

![dos](https://cloud.githubusercontent.com/assets/14174212/9747169/f559c67c-5630-11e5-9ec9-1e04bf137da5.png)


![cinco](https://cloud.githubusercontent.com/assets/14174212/9747291/b827f700-5631-11e5-868b-256b93096105.png)

Att,

John J.

**Comment by jokla** [comment]
Hi!

For this error:
![uno](https://cloud.githubusercontent.com/assets/14174212/9747078/65570b48-5630-11e5-8d0f-e86e5437986b.png)

you should enter in the folder of vreprosbridge and after do the checkout:

'cd vrep_ros_bridge/'
'git checkout indigo-devel'


But there is something strange, it seems ROS does not find the packages in your src folder... try to source it manually in a new terminal:

'source /home/jokla/catkin_ws/devel/setup.bash'

and updated the db (not sure this help):
'sudo updatedb'

1) If you digit  in a terminal 'roscd' in which folder you finish?

2) Can you tell me the result of:

'echo $ROS_PACKAGE_PATH' ?

You should have something like:
'/home/jokla/catkin_ws/src:/opt/ros/indigo/share:/opt/ros/indigo/stacks'

Giovanni

**Comment by johnjavz** [comment]
Hi  Giovanni

1) If you digit in a terminal 'roscd' in which folder you finish?
                            ~/catkin_ws/devel$

2) Can you tell me the result of:        'echo $ROS_PACKAGE_PATH' ?

/home/john/catkin_ws/src:/opt/ros/indigo/share:/opt/ros/indigo/stacks

Thanks. 

John J

**Comment by johnjavz** [comment]
Hi  Giovanni

git checkout indigo-devel in the source:    'cd vrep_ros_bridge/'
                                                                  'git checkout indigo-devel' 
ok
![uno](https://cloud.githubusercontent.com/assets/14174212/9756133/5cb4cada-569d-11e5-9923-09df222830dd.png)


catkin_make  and 
catkin_make --pkg vrep_ros_bridge --cmake-args -DCMAKE_BUILD_TYPE=RelWithDebInfo

This error:  cmake_failed

![tres1](https://cloud.githubusercontent.com/assets/14174212/9756177/b21c6ae6-569d-11e5-820e-9d05d8468396.png)

![cuatro](https://cloud.githubusercontent.com/assets/14174212/9756195/d079e9c8-569d-11e5-9186-446b37684166.png)

Thanks,

Att

John J

**Comment by jokla** [comment]
Probably the path to Vrep is wrong:
#V-REP
export VREP_ROOT_DIR=/home/jokla/Romeo/SOFT/3rd_PARTY/V-REP

It should point at this directory:
![textfile](https://cloud.githubusercontent.com/assets/6526050/3525446/f226bd56-0772-11e4-8b52-9922e936b0a6.png)

Can you check it?

**Comment by johnjavz** [comment]
Hi Giovanni.

I have tested and working properly. Compiling only 2 times and restarting the computer. and compile again.
It is something strange in Ubuntu 14.04.

Thanks.

John J.
