### ISSUE TITLE
'RosBridge': loading failed

### ISSUE THREAD

**Issue by koalamaster** [lagadic/vrep_ros_bridge#64]
Plugin 'RosBridge': loading...
./vrep.sh: line 33: 70711 Segmentation fault      (core dumped) "$dirname/$appname" "${PARAMETERS[@]}"

**Comment by jokla** [comment]
Hi! which version of V-REP and Ubuntu are you using?

**Comment by koalamaster** [comment]
V-REP 3.4.0 pro-edu
Ubuntu 14.04

**Comment by fspindle** [comment]
The bridge is not working with v-rep 3.4.0 see #62

**Comment by koalamaster** [comment]
Thank you

**Comment by jimis093** [comment]
hey can you help me to install ros bridge plz ? the tutorial doesnt help me .
