### ISSUE TITLE
Relicense under Apache-compatible license

### ISSUE THREAD

**Issue by berezovskyi** [lagadic/vrep_ros_bridge#67]
Hello,

We are developing an Apache 2 licensed OSS project. Unfortunately, it means we can't make use of GPL software.

The original bindings from V-REP are now relicensed under BSDv2: https://github.com/CoppeliaRobotics/remoteApiBindings/issues/2

Would it be possible for you to relicense the bridge under any license, compatible with Apache (MPL and EPL are two compat copyleft licenses if you wish it to remain copyleft), please?

/Andrew

**Comment by fspindle** [comment]
Will be done ASAP
