### ISSUE TITLE
Compatible with ROS Kinetic or Lunar? (Ubuntu 16.04)

### ISSUE THREAD

**Issue by javiribera** [lagadic/vrep_ros_bridge#68]
The [instructions](https://github.com/lagadic/vrep_ros_bridge#ros) indicate we should use ROS Hydro or Indigo. However, [Indigo only supports Ubuntu 14.04](http://wiki.ros.org/indigo/Installation/Ubuntu#Installation). Is the "V-Rep ROS Bridge" also compatible with modern versions of ROS, such as Lunar or Kinetic? These would allow us to use modern Ubuntu versions, as [Kinetic supports Ubuntu 16.04](http://wiki.ros.org/kinetic#Platforms) and [Lunar suports Ubuntu 17.04](http://wiki.ros.org/lunar#Platforms).

Thank you

**Comment by fspindle** [comment]
Should be compatible even if the doc is out of date. Don't hesitate to contribute with a PR
